import {Pork} from './app/shared/models/Pork';
import { Tag } from './app/shared/models/Tag';

export const sample_Porks: Pork[] = [
    {
        id:'1',
        name: 'Pork tenderloin',
   
        price: 10,
        favorite: false,
        stars: 4.5,
        imageUrl: 'assets/img/pork1.png',
        tags: ['Meat'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'2',
        name: 'Pork sirloin',
        price: 20,
     
        favorite: true,
        stars: 4.7,
        imageUrl: 'assets/img/pork2.png',
        tags: ['Meat'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'3',
        name: 'Pork butt',
        price: 5,
      
        favorite: false,
        stars: 3.5,
        imageUrl: 'assets/img/pork3.png',
        tags: ['Meat'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'4',
        name: 'Pork neck',
        price: 2,
        favorite: true,
        stars: 3.3,
        imageUrl: 'assets/img/pork4.png',
        tags: ['Meat'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'5',
        name: 'Pork liver',
        price: 11,
        favorite: false,
        stars: 3.0,
        imageUrl: 'assets/img/pork5.png',
        tags: ['Offal'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'6',
        name: 'Pork intestines',
        price: 9,
        favorite: false,
        stars: 4.0,
        imageUrl: 'assets/img/pork6.png',
        tags: ['Offal'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'7',
        name: 'Pork heart',
        price: 9,
        favorite: false,
        stars: 4.0,
        imageUrl: 'assets/img/pork7.png',
        tags: ['Offal'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'8',
        name: 'Pork spleen',
        price: 9,
        favorite: false,
        stars: 4.0,
        imageUrl: 'assets/img/mam.png',
        tags: ['Offal'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'9',
        name: 'Pepper-marinated pork',
        price: 9,
        favorite: false,
        stars: 4.0,
        imageUrl: 'assets/img/pork8.png',
        tags: ['Marinatedpork'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'10',
        name: 'Tenderized marinated pork',
        price: 9,
        favorite: false,
        stars: 4.0,
        imageUrl: 'assets/img/pork9.png',
        tags: ['Marinatedpork'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'11',
        name: 'Sesame oil-marinated pork',
        price: 9,
        favorite: false,
        stars: 4.0,
        imageUrl: 'assets/img/pork10.png',
        tags: ['Marinatedpork'],
        kilo: 'กก./1แพ็ค',
      },
      {
        id:'12',
        name: 'Three-flavor marinated pork',
        price: 9,
        favorite: false,
        stars: 4.0,
        imageUrl: 'assets/img/pork11.png',
        tags: ['Marinatedpork'],
        kilo: 'กก./1แพ็ค',
      },
      
    ]
    
    export const sample_tags:Tag[] = [
      { name: 'All', count: 12 },
      { name: 'Meat', count: 4 },
      { name: 'Offal', count: 4 },
      { name: 'Marinated', count: 4 },
    ]